journal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^users/', include('users.urls', namespace='users')),
]

learning_logs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	# homepage 
	url(r'^$', views.index, name='index'),
	url(r'^topics/$', views.topics, name='topics'),
	url(r'^topics/(?P<topic_id>\d+)/$' , views.topic, name='topic'),
	# page for adding a new topic
	url(r'^new_topic/$', views.new_topic, name = 'new_topic'),
	# page for adding a new entry
	url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
	# page for editing entries
	url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry')
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login


from . import views 


urlpatterns = [
	url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
	url(r'^logout/$', views.logout_view, name='logout'),
	url(r'^register/$', views.register, name='register'),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
	""" a topic the user if learning about"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User)

	def __str__(self):
		""" return a string representation of the model"""
		return self.text

class Entry(models.Model):
	""" information about what you learnt in regard with the topic"""
	topic = models.ForeignKey( Topic)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		""" return a string representation of the model"""
		return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect 
from django.core.urlresolvers import reverse
from . models import Topic, Entry
from . forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required

def index(request):
	""" the home_page for learning log"""
	return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
 	"""Show all topics."""
 	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
 	context = {'topics': topics}
 	return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
	""" show a single topic and all its entries """
	topic = Topic.objects.get(id=topic_id)
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'learning_logs/topic.html', context)
@login_required
def new_topic(request):
	""" allow users to create a new topic"""
	if request.method != 'POST':
		# No data submitted ; create a blank form.
		form = TopicForm()
	else:
		# post data submitted; process data
		form = TopicForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))

	context = {'form': form}

	return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request,topic_id):
	""" allow users to create a new entry associated with a given topic"""
	topic = Topic.objects.get(id=topic_id)

	if request.method != 'POST':
		# no data submitted; create a blank form
		form = EntryForm()
	else:
		# post data submitted; process data
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

	context = {'topic': topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	""" allow user to edit the entries that they have already added"""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic

	if request.method != 'POST':
		# initial request; pre fill form with the current entry
		form = EntryForm(instance=entry)
	else:
		# post data submitted and process it
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'learning_logs/edit_entry.html', context)



	

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

def logout_view(request):
	""" log the user out"""
	logout(request)
	return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
	""" register a new user"""
	if request.method != 'POST':
		# display blank registration form
		form = UserCreationForm()
	else:
		# process completed form
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# log the user in and then redirect to homepage
			authenticated_user = authenticate(username=new_user.username,
				password=request.POST['password']
				)
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('learning_logs:index'))

	context = {'form': form}
	return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style type="text/css">
		ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

/* Change the link color to #111 (black) on hover */
li a:hover {
    background-color: #111;
}
	</style>
</head>
<body style="background-color:white;, padding: 20px; ">
	<a href="{% url 'learning_logs:index' %}">Learning Log</a>

<ul>
  <li><a href="{% url 'learning_logs:index' %}">Home</a></li>
  <li><a href="{% url 'learning_logs:topics' %} ">topic</a>
  </li>
  <li>
    {% if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %} "></a>
    {% else %}
    <a href="{% url 'users:login' %} "> Log in</a>
    {% endif %}
  </li>

  <li><a href="{% url 'learning_logs:new_topic' %}">New topic</a></li>
  <li>
      <a href="{% url 'users:register' %}">Register</a>
  </li>
</ul>
	{%  block content %}

	{% endblock content %}

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>
	<a href="{% url 'learning_logs:topic' topic.id %}"></a>{{ topic }}
</p>
<p> Edit entry:</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
 {% csrf_token %}
 {{ form.as_p }}
 <button name="submit">save changes</button>
 </form>

 {% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body style="padding: 30px;">
	{% block content %}
	{% csrf_token %}
	<span>to get started login below</span>

<form class="form-horizontal" role="form">
  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Email:</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="email" placeholder="Enter email">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="pwd">Password:</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="pwd" placeholder="Enter password">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label><input type="checkbox"> Remember me</label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
</form>
	{% endblock content %}

</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<h1> create a new entry for this topic</h1>
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

 <p>Add a new entry:</p>
 <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>

 	{% csrf_token %}
 	{{ form.as_p }}
 	<button name='submit'>add entry</button>
 </form>




{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<h1> create a new topic. learning is all about keeping track of what you have learnt </h1> 



<p> Add a new topic:</p>
<form action="{% url 'learning_logs:new_topic' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button name="submit">add topic</button>
	
</form>



{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p> Topic: {{ topic}}</p>


<p>Entries:</p>
<p>
	<a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
<ul>
	{% for entry in entries %}
	<li>
		<p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
		<p>{{ entry.text|linebreaks }}</p>
		<p>
			<a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
		</p>
	</li>
	{% empty %}
	<li>
		there are no entries for this topic yet
	</li>
	{% endfor %}
</ul>



{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

<!DOCTYPE html>
<html>
<head>
	{% block content %}
	<title>topics</title>
	<style type="text/css">
		ul {
    		list-style-type: none;
    		margin: 0;
    		padding: 0;
			}
	</style>
</head>
<body>
	<h2> Topics </h2>
	{% if topics %}
	
	<ul>
		{% for topic in topics %}
		<li>
			<a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }}</a>
		</li>
		{% empty %}
		<li>no topics have been added as per now. create your own topic today</li>
		{% endfor %}
	</ul>
	{% else %}
	<p> no topics have been added yet</p>
	{% endif %}
	<br>
	<h2>create a new topic below</h2>
	<br>
	<button style="background-color: grey;"><a href="{% url 'learning_logs:new_topic' %}" style="text-decoration-color: blue;"> Add a new topic</a></button>
		
	
		

	{% endblock content %}
</body>
</html>

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% block content %}
{% if form.errors %}
<p>your username and password didn't match. Please try again</p>
{% endif %}

<form method="post", action="{% url 'users:login' %}">

{% csrf_token %}
{{ form.as_p }}

<button name="submit">Log in</button>
<input type="hidden" name="next" value="{% url 'learning_logs:index' %} " /> 
</form>	

{% endblock content %}	

users/templates/users/register.html
{% extends "learning_logs/base.html" %}

{% block content %}

<form method="post", action="{% url 'users:register' %}">

	{% csrf_token %}
	{{ form.as_p }}

	<button name="submit">register
		
	</button>
	<input type="hidden" name="next" value="{% url 'learning_logs:index'%} "/>
	
</form>
{% endblock content %}